Repository KalicoCrew/kalico, pull requests merged in 2024-06, with the labels that each got.

#224 shaper_calibrate: store accel_per_hz
  klippy/extras/resonance_tester.py
  klippy/extras/shaper_calibrate.py
  scripts/calibrate_shaper.py
Labels: blocked

#306 feat: enable [exclude_object] by default
  README.md
  docs/Config_Reference.md
  docs/Danger_Features.md
  klippy/extras/exclude_object.py
  klippy/extras/force_move.py
  klippy/extras/respond.py
  klippy/klippy.py
Labels: ready-to-go

#304 bugfix: sensorless return to run current
  klippy/extras/homing.py
  klippy/extras/tmc.py
Labels: ready-to-go

#303 Don't use incomplete clock sync for SPI temperature; always warn
  klippy/clocksync.py
  klippy/extras/spi_temperature.py
Labels: work-in-progress

#309 Update MPC.md
  docs/MPC.md
Labels: work-in-progress

#305 gcode_macro: adds RELOAD_GCODE_MACROS
  README.md
  docs/Danger_Features.md
  docs/G-Codes.md
  klippy/configfile.py
  klippy/console.py
  klippy/extras/gcode_macro.py
  test/klippy/gcode_jinja2_ext_do.test
Labels: ready-to-go

#314 feat/app_name: adds a APP_NAME constant, display during boot time
  klippy/klippy.py
  klippy/webhooks.py
  scripts/buildcommands.py
Labels: ready-to-go

#312 feat/resonance_tester: accepts ACCEL_PER_HZ in TEST_RESONANCES
  README.md
  docs/G-Codes.md
  klippy/extras/resonance_tester.py
Labels: testing-needed

#311 bugfix/heaters: auto detect generic heaters when looking up heater objects
  klippy/extras/heaters.py
Labels: ready-to-go

#310 bugfix/fan: shutdown shouldnt use max_power when hardware pwm is not set
  klippy/extras/fan.py
  test/klippy/fan_pwm_scaling.cfg
Labels: ready-to-go
